# Generated by Django 5.1.3 on 2024-12-09 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
